package com.callbloqued.sift.data.local.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

/**
 * Room DAO for inserting and observing [BlockedCallLogEntity] records.
 *
 * Insert is a suspending function to allow callers to run it on a background dispatcher
 * without blocking the main thread. The query returns a [Flow] so that the UI layer (F4)
 * can observe updates reactively without manual refresh logic.
 *
 * The concrete implementation is generated by Room's KSP processor and registered in
 * [AppDatabase].
 */
@Dao
interface BlockedCallLogDao {

    /**
     * Inserts a new blocked-call event record into the database.
     *
     * Uses [OnConflictStrategy.ABORT] (the default) because each event has an auto-generated
     * primary key and conflicts should never occur in practice; if one does it surfaces as an
     * exception rather than silently discarding data.
     *
     * @param entity The [BlockedCallLogEntity] to persist. Set [BlockedCallLogEntity.id] to 0
     *   so that Room generates a new id automatically.
     */
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(entity: BlockedCallLogEntity)

    /**
     * Returns a [Flow] that emits all blocked-call log entries ordered by most-recent first.
     *
     * Room re-emits the full list whenever any row in `blocked_call_log` is inserted or deleted,
     * making the flow suitable for direct collection by a ViewModel.
     *
     * @return A [Flow] emitting the complete list of [BlockedCallLogEntity] rows, newest first.
     */
    @Query("SELECT * FROM blocked_call_log ORDER BY timestamp DESC")
    fun observeAll(): Flow<List<BlockedCallLogEntity>>
}
