package com.callbloqued.sift.data.local.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update

/**
 * Room DAO for reading and writing [CallAttemptEntity] records.
 *
 * All operations are suspending to allow callers to run them inside a coroutine on a
 * background dispatcher without blocking the main thread. The concrete implementation is
 * generated by Room's KSP processor and registered in [AppDatabase].
 */
@Dao
interface CallAttemptDao {

    /**
     * Looks up the blocking record for the given phone number.
     *
     * @param phoneNumber Phone number in E.164 format.
     * @return The matching [CallAttemptEntity], or `null` if no record exists for this number.
     */
    @Query("SELECT * FROM call_attempts WHERE phone_number = :phoneNumber LIMIT 1")
    suspend fun findByPhoneNumber(phoneNumber: String): CallAttemptEntity?

    /**
     * Inserts a new attempt record for a caller that has never been seen before.
     *
     * Uses [OnConflictStrategy.ABORT] to surface accidental duplicate inserts as an exception
     * rather than silently overwriting the existing first-attempt timestamp. Callers must check
     * [findByPhoneNumber] before calling this method.
     *
     * @param entity The new [CallAttemptEntity] to persist.
     */
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(entity: CallAttemptEntity)

    /**
     * Updates an existing attempt record (last-seen timestamp and counter) for a returning caller.
     *
     * The entity is matched by its primary key ([CallAttemptEntity.phoneNumber]).
     *
     * @param entity The [CallAttemptEntity] with updated fields to write back to the database.
     */
    @Update
    suspend fun update(entity: CallAttemptEntity)
}
