package com.callbloqued.sift.data.local.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

/**
 * Room DAO for reading and writing [ManualListEntity] records.
 *
 * [upsert] uses [OnConflictStrategy.REPLACE] so that adding a number to one list automatically
 * replaces any existing entry for that number (whether it was in the same or the opposite list),
 * maintaining the mutual-exclusivity invariant enforced by the primary key on [ManualListEntity].
 *
 * All suspending functions are designed to run on a background dispatcher. The [Flow]-returning
 * query re-emits whenever any row in `manual_list` changes, making it suitable for direct
 * collection by a ViewModel without manual refresh logic.
 *
 * The concrete implementation is generated by Room's KSP processor and registered in [AppDatabase].
 */
@Dao
interface ManualListDao {

    /**
     * Inserts or replaces a manual list entry.
     *
     * If a row with the same [ManualListEntity.phoneNumber] already exists — regardless of
     * which list it currently belongs to — it is replaced by [entity]. This is the mechanism
     * that moves a number from one list to the other atomically.
     *
     * @param entity The [ManualListEntity] to persist.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(entity: ManualListEntity)

    /**
     * Deletes the entry for [phoneNumber] from whichever list it belongs to.
     *
     * No-ops silently if no entry for [phoneNumber] exists.
     *
     * @param phoneNumber The phone number in E.164 format to remove.
     */
    @Query("DELETE FROM manual_list WHERE phone_number = :phoneNumber")
    suspend fun delete(phoneNumber: String)

    /**
     * Returns the entry for [phoneNumber] that has the given [listType], or null if not present.
     *
     * Used by [com.callbloqued.sift.data.repository.ManualListRepositoryImpl] to implement the
     * point lookups [isBlacklisted] and [isWhitelisted]. Filtering by both columns in SQL avoids
     * an extra in-memory check after the query returns.
     *
     * @param phoneNumber The phone number in E.164 format to look up.
     * @param listType The list type name to filter by (e.g. `"BLACKLIST"` or `"WHITELIST"`).
     * @return The matching [ManualListEntity], or null if the number is not in [listType].
     */
    @Query("SELECT * FROM manual_list WHERE phone_number = :phoneNumber AND list_type = :listType LIMIT 1")
    suspend fun findByNumberAndType(phoneNumber: String, listType: String): ManualListEntity?

    /**
     * Returns a [Flow] that emits all entries whose [ManualListEntity.listType] matches [listType],
     * ordered by [ManualListEntity.addedAt] descending (most-recently-added first).
     *
     * Room re-emits the full filtered list whenever any row in `manual_list` is inserted,
     * updated, or deleted.
     *
     * @param listType The list type name to filter by (e.g. `"WHITELIST"`).
     * @return A [Flow] emitting [ManualListEntity] lists for [listType], newest first.
     */
    @Query("SELECT * FROM manual_list WHERE list_type = :listType ORDER BY added_at DESC")
    fun observeByType(listType: String): Flow<List<ManualListEntity>>
}
